### PR TITLE
Added Sky Drop.  Current weight test is >= 200kg, needs to be confirmed

### PR DESCRIPTION
**Pull request by Tapin42**
Bulba says both "[greater than 200kg are immune](http://bulbapedia.bulbagarden.net/wiki/Sky_Drop_%28move%29#Generation_VI)" and "[200kg or greater are immune](http://bulbapedia.bulbagarden.net/wiki/List_of_Pok%C3%A9mon_by_weight#440.9_lbs._to_451.4_lbs._.28200.0_kg_to_204.7_kg.29)".

This is actually important for (eg) Virizion, who weighs exactly 200kg.  Either it'll be immune, or hit for 4x effective damage.

Addresses #40.

### CODE REVIEW

**Comment by Tapin42** [comment]
8:31 AM <•OmegaDonut> it's 200kg inclusive
8:31 AM <•OmegaDonut> crustle is the same weight and sky drop fails on it
8:31 AM <•OmegaDonut> I've tested

**Comment by augmt** [comment]
Can you test if Sky Drop does damage if the target is holding an Iron Ball?

**Comment by Tapin42** [comment]
I'll check it out.  I also didn't take Gravity into account, so I need to update for that as well.

**Comment by Tapin42** [comment]
Haven't tested it personally yet, but the chatter on the channel is:
- Gravity stops Sky Drop from working (0% dam)
- Iron ball has no effect whether it's held by the attacker or defender
- Air balloon has no effect (and pops)
- Ingrain (which we're not going to account for) will stop Sky Drop
- If the target's ally uses ally switch, the target will indeed be swapped out of the sky (the ally ends up in the sky), but we're not going to account for that

So it looks like Gravity is the only thing I need to add, unless someone tests and tells me any of this list is wrong or incomplete.

**Comment by Tapin42** [comment]
Gravity's added, this should be good to go at this point.

**Pull request merged**
